using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEditorInternal;
using UnityEngine;

namespace Module.Core.Constants.Generator
{
    public class TagConstantsGenerator
    {
        private const string className = "Tag";
        private static readonly string savePath = $"Assets/Scripts/Module/Core/Constants/{className}.cs";

        [MenuItem("Tools/TagNameGenerator", false, -99)]
        private static void ManualGenerate()
        {
            Generate();
            Debug.Log($"{savePath}にTagの定数ファイルを作成しました。");
        }

        [InitializeOnLoadMethod]
        private static void Generate()
        {
            var builder = new CodeBuilder();
            builder.AddAutoGenerated(nameof(TagConstantsGenerator));

            //タグ名を取得
            List<(string field, string real)> tags = InternalEditorUtility.tags
                .Select(tagName => (tagName.Replace(" ", String.Empty), tagName))
                .ToList();

            using (builder.CreateBlockScope($"namespace {nameof(Module.Core.Constants)}"))
            {
                //タグ名を生成
                using (builder.CreateBlockScope($"public sealed class {className}"))
                {
                    foreach ((string field, string real) tag in tags)
                    {
                        builder.NewLine($"public const string {tag.field} = \"{tag.real}\";");
                    }
                }
            }

            CreateFile(builder);
        }

        private static void CreateFile(CodeBuilder builder)
        {
            using (var stream = File.Create(savePath))
            {
                var generatedCode = builder.ToString();
                var bytes = new UTF8Encoding(true).GetBytes(generatedCode);
                stream.Write(bytes);
            }

            AssetDatabase.Refresh();
        }
    }
}