// Copyright (c) 2022 Jonathan Lang

//---------- -------------------------- -------
//---------- !!! AUTOGENERATED CONTENT !!! -------
//---------- -------------------------- -------

//Runtime Monitoring
//File generated: 2024-10-10 18:02:49Z
//Please dont change the contents of this file. Otherwise IL2CPP runtime may not work with runtime monitoring!
//Ensure that this file is located in Assembly-CSharp. Otherwise this file may not compile.
//If this file contains any errors please contact me and/or create an issue in the linked repository.
//https://github.com/JohnBaracuda/Runtime-Monitoring

#if ENABLE_IL2CPP && !DISABLE_MONITORING

internal class IL2CPP_AOT_N8K2OXSRO5RMAXUHB695
{
    //Value Processor Method Definitions

    [UnityEngine.Scripting.PreserveAttribute]
    [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.NoOptimization)]
    private static void AOT()
    {
        //  [Field Definitions] 

        // Baracuda.Monitoring.Modules.SystemMonitor::_operatingSystem (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_operatingSystemFamily (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_deviceType (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_deviceModel (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_deviceName (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_processorType (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_processorFrequency (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_processorCount (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_systemMemory (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_graphicsDeviceName (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_graphicsDeviceType (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_graphicsMemorySize (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_graphicsMultiThreaded (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_batteryLevel (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_batteryStatus (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_dataPath (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_persistentDataPath (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_consoleLogPath (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_streamingAssetsPath (System.String)
        // Baracuda.Monitoring.Modules.SystemMonitor::_temporaryCachePath (System.String)
        // Module.Gimmick.Sound.PhysicsSoundEffector::collisionPowerList (System.Collections.Generic.List<System.Single>)
        Baracuda.Monitoring.IL2CPP.IL2CPPTypeDefinitions.TypeDefField<System.Object, System.Object>();

        // Baracuda.Monitoring.Modules.FPSMonitor::_fps (System.Single)
        Baracuda.Monitoring.IL2CPP.IL2CPPTypeDefinitions.TypeDefField<System.Object, System.Single>();

        //  [Property Definitions] 

        // Baracuda.Monitoring.Modules.FPSMonitor::TargetFrameRate (System.Int32)
        // Baracuda.Monitoring.Modules.FPSMonitor::Vsync (System.Int32)
        Baracuda.Monitoring.IL2CPP.IL2CPPTypeDefinitions.TypeDefProperty<System.Object, System.Int32>();

        // Baracuda.Monitoring.Modules.ConsoleMonitor::Console (System.Collections.Generic.Queue<System.String>)
        // Baracuda.Monitoring.Modules.ConsoleMonitor::LastLogStacktrace (System.String)
        Baracuda.Monitoring.IL2CPP.IL2CPPTypeDefinitions.TypeDefProperty<System.Object, System.Object>();

        //  [Collection Definitions] 

        // System.Collections.Generic.Queue<System.String>
        Baracuda.Monitoring.IL2CPP.IL2CPPTypeDefinitions.TypeDefEnumerable<System.Object>();

        // System.Collections.Generic.List<System.Single>
        Baracuda.Monitoring.IL2CPP.IL2CPPTypeDefinitions.TypeDefEnumerable<System.Single>();

        // System.Collections.Generic.List<System.Single>
        Baracuda.Monitoring.IL2CPP.IL2CPPTypeDefinitions.TypeDefList<System.Single>();
    }
}

#endif //ENABLE_IL2CPP && !DISABLE_MONITORING

//----------------------------------------------------------------------------------------------------------------------

//--- Stats ---

//General

//Monitored Member:               26
//Monitored Member Instance:      26

//MemberInfo

//Monitored Fields:               22
//Monitored Fields Instance:      22
//Monitored Properties:            4
//Monitored Properties Instance:   4

//Monitored Types

//Monitored float:                 1
//Monitored int:                   2
//Monitored List<float>:           1
//Monitored Queue<string>:         1
//Monitored string:               21

//----------------------------------------------------------------------------------------------------------------------

//If this file contains any errors please contact me and/or create an issue in the linked repository.
//https://github.com/JohnBaracuda/Runtime-Monitoring