// <auto-generated>
// This code was generated by SoundKeyGenerator.
// </auto-generated>


namespace Core.Sound
{
	public enum SoundKey
	{
		Foot,
		GateOpen,
		WallRotate,
		Box,
		BreakFloor,
		ElectricShock,
		Jump,
		Switch,
		FallWind,
		Poison,
		ButtonSelect,
		ButtonSubmit,
	}
	
	public enum MixerType
	{
		BGM,
		SE,
	}
}