// <auto-generated>
// This code was generated by SoundKeyGenerator.
// </auto-generated>


namespace Core.Sound
{
	public enum SoundKey
	{
		Foot,
		GateOpen,
		WallRotate,
		Box,
		BreakFloor,
		ElectricShock,
		Jump,
		Switch,
		FallWind,
		Poison,
		ButtonSelect,
		ButtonSubmit,
		Heliport,
		MachineEnvironment01,
		CalmRoom,
		MagicPower,
		OpenLock,
		OpenHugeGate,
		JumpBoard,
		HubGateLight,
		Fall,
		Bomb,
		LastBGMSample,
		TutorialBGM1,
		TutorialBGM2,
	}
	
	public enum MixerType
	{
		BGM,
		SE,
	}
}