// <auto-generated>
// This code was generated by LayerConstantsGenerator.
// </auto-generated>


namespace Constants
{
	public sealed class Layer
	{
		public const int Default = 0;
		public const int TransparentFX = 1;
		public const int IgnoreRaycast = 2;
		public const int Water = 4;
		public const int UI = 5;
		public const int Gravity = 6;
		public const int Base = 7;
		public const int Holdable = 8;
		public const int IgnoreGravity = 9;
		public const int IgnoreGimmick = 10;
		
		public sealed class Mask
		{
			public const int Default = 1;
			public const int TransparentFX = 2;
			public const int IgnoreRaycast = 4;
			public const int Water = 16;
			public const int UI = 32;
			public const int Gravity = 64;
			public const int Base = 128;
			public const int Holdable = 256;
			public const int IgnoreGravity = 512;
			public const int IgnoreGimmick = 1024;
		}
	}
}