// <auto-generated>
// This code was generated by TagConstantsGenerator.
// </auto-generated>


namespace Constants
{
	public sealed class Tag
	{
		public const string Untagged = "Untagged";
		public const string Respawn = "Respawn";
		public const string Finish = "Finish";
		public const string EditorOnly = "EditorOnly";
		public const string MainCamera = "MainCamera";
		public const string Player = "Player";
		public const string GameController = "GameController";
		public const string Wall = "Wall";
		public const string BatteryBox = "BatteryBox";
		public const string LevelSegment = "LevelSegment";
		public const string UnJumpable = "UnJumpable";
	}
}